// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    ElButton: typeof import('element-plus/es')['ElButton']
    HelloWorld: typeof import('./components/HelloWorld.vue')['default']
    TeleportTest: typeof import('./components/TeleportTest.vue')['default']
    TeleportTest2: typeof import('./components/TeleportTest2.vue')['default']
    Test1: typeof import('./components/Test1.vue')['default']
    Test2: typeof import('./components/Test2.vue')['default']
    Test3: typeof import('./components/Test3.vue')['default']
    Test4: typeof import('./components/Test4.vue')['default']
    VanButton: typeof import('vant/es')['Button']
    VanDialog: typeof import('vant/es')['Dialog']
    VanSkeleton: typeof import('vant/es')['Skeleton']
    VuePortals: typeof import('./components/VuePortals.vue')['default']
  }
}

export { }
